Form
michaeleggboy/personal_repository pull request #7
Opened 2020-06-10 17:30 UTC by michaeleggboy

Commits centered around the functionality of comment form.

2020-06-10 20:20 UTC, MarsWang42 requested changes
Overall looks great, just need some small tweaks :)
Do not merge this PR before I approve

2020-06-10 20:20 UTC, MarsZ42 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +      i= 0;
Like I mentioned before, this might not behave as you expected when there’re multiple users using the app. I’ll leave it up to you whether or not use a random number here :)

2020-06-10 20:20 UTC, MarsZ42 commented on portfolio/src/main/java/com/google/sps/servlets/DisplayCommentsServlet.java
> +        response.setContentType("application/json;");
If we only need the first 5 comments, use limit query instead
https://cloud.google.com/datastore/docs/concepts/queries#cursors_limits_and_offsets

2020-06-10 20:20 UTC, MarsZ42 commented on portfolio/src/main/java/com/google/sps/servlets/DisplayCommentsServlet.java
> +        numComments= Integer.parseInt(request.getParameter("numComments"));
Cannot find where this method is called?

2020-06-11 17:21 UTC, MarsWang42 approved these changes
Great job!

2020-06-11 17:21 UTC, merged