Servlet setup
michaeleggboy/personal_repository pull request #8
Opened 2020-06-10 17:31 UTC by michaeleggboy

Commits centered around the functionality of servlet setup.

2020-06-10 20:24 UTC, MarsWang42 requested changes
Do not merge the PR before I approved.

2020-06-10 20:24 UTC, MarsZ42 commented on portfolio/src/main/java/com/google/sps/servlet/NewCommentServlet.java
> +        /* String userEmail= userService.getCurrentUser().getEmail(); */
I know it’s sometimes easier to just comment out something you need for testing things out, but remember to remove them when you trying to merge them into master. Just add them back when you need them.

2020-06-10 20:24 UTC, MarsZ42 commented on portfolio/src/main/webapp/script.js
> +function onLoadII(){
Rename these method to something descriptive

2020-06-10 20:24 UTC, MarsZ42 commented on portfolio/src/main/webapp/script.js
> +    location.replace("/login");
It might not be a good idea to share login and out in one url. Try using different paths for them.

2020-06-11 18:06 UTC, michaeleggboy commented
Everything should be good now, ready to merge

2020-06-11 18:48 UTC, MarsWang42 approved these changes

2020-06-11 20:34 UTC, merged